### ISSUE TITLE
Raised `Http404` are logged as error

### ISSUE THREAD

**Issue by browniebroke** [namespace-ee/django-datadog-logger#17]
* Django DataDog Logger version: 0.6.2
* Python version: 3.11
* Operating System: Ubuntu (Docker)

### Description

We're using Datadog with Sentry and installed the `ErrorLoggingMiddleware` from this library. We now have errors appearing in Sentry which are logged by this middleware for each places where we `raise Http404("not found")`.

Ideally we don't want these logged as errors, warning level is probably sufficient. I was going to investigate filtering them, but I guess other folks might have the same problem, and it might be better to fix here.

### What I Did

Setup a Django project with this package and Sentry, then create a view like this:

```
def some_view(request):
    raise Http404()
```

-> Error is logged in Sentry.

**Comment by jacekbj** [comment]
@browniebroke This is because `ErrorLoggingMiddleware` logs every exception, even those that are explicitly handled by Django and transformed into 404 or 400 responses (see this function: https://github.com/django/django/blob/4eb9c3d90aff55182151b6be0122f7d0b28832fd/django/core/handlers/exception.py#L63).

A workaround I used was to extend the `ErrorLoggingMiddleware` to ignore those exceptions:

```python
class CustomErrorLoggingMiddleware(ErrorLoggingMiddleware):
    def process_exception(self, request, exception):
        # Skip logging of these exceptions
        # They're handled by Django middleware wrapper
        if isinstance(
            exception,
            (PermissionDenied, Http404, MultiPartParserError, BadRequest, SuspiciousOperation),
        ):
            return

        super().process_exception(request, exception)
```
